# action.yaml
name: "Parlay Github Action"
description: "Runs Parlay on the given input file using the given enricher and outputs it in your given output file"
icon: arrow-down-left
color: gray-dark
inputs:
  input_file_name:
    description: "Name of the input SBOM file to enrich"
    required: true
  enricher:
    description: "The enricher used to enrich the parlay sbom. Currently parlay supports ecosystems, snyk, scorecard(openssf scorecard)"
    required: true
    default: ecosystems
  output_file_name:
    description: "Name of the output file to save the SBOM enriched using the parlay's enricher"
    required: true
outputs:
  output_file_name:
    description: "Prints the output file"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.input_file_name }}
    - ${{ inputs.enricher }}
    - ${{ inputs.output_file_name }}
