on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: We test it locally with act
    steps:
      - name: Checkout git branch
        uses: actions/checkout@v1
        
      - name: Run Parlay locally and get result
        uses: krishnaduttPanchagnula/parlayaction@main
        id: parlay
        with:
          input_file_name: ./cyclonedx.json
          enricher: ecosystems
          output_file_name: enriched_cyclonedx.json